INSERT INTO watches (brand, model, price, description)
VALUES 
  ('Rolex', 'Datejust', 6000, 'Introducing the iconic Rolex Datejust, a timeless masterpiece that seamlessly blends classic design with cutting-edge technology. This legendary timepiece is renowned for its elegant aesthetics, precision engineering, and unmatched reliability. The Datejust boasts a distinctive cyclops lens over the date display, ensuring optimal legibility. Crafted with the finest materials, it exudes luxury and sophistication, making it the perfect companion for any occasion. Elevate your style with the Rolex Datejust, a symbol of refinement and prestige.'),
  ('Rolex', 'Submariner', 9000, 'Dive into the world of horological excellence with the Rolex Submariner. Born for the depths, this legendary timepiece is the epitome of precision, durability, and style. Engineered for professional divers, the Submariner features a unidirectional rotatable bezel, ensuring accurate elapsed time measurement during underwater expeditions. Its luminescent markers and hands provide unparalleled legibility even in the darkest depths. Crafted with robust materials, the Submariner is a testament to Rolex''s commitment to quality and performance. Whether you''re exploring the ocean''s depths or making a statement on land, the Rolex Submariner is the ultimate companion for the modern adventurer.'),
  ('Rolex', 'Daytona', 15000, ' Embrace the legacy of speed with the Rolex Daytona, a legendary racing watch. Born from a passion for motorsports, this timepiece combines precision engineering with timeless style. The Daytona is a symbol of performance, designed to keep pace with the fastest moments in life.'),
  ('Rolex', 'Cellini', 12000, 'Experience the spirit of the racetrack with the Rolex Cellini, a watch that exudes elegance and power. Inspired by the world of racing, this timepiece captures the essence of speed in a refined, sophisticated form. The Cellini is a testament to the fusion of precision and luxury.'),
  ('Rolex', 'Day-Date', 35000, 'The Rolex Day-Date stands as an icon of prestige and luxury. With its distinctive day and date displays, this watch has graced the wrists of world leaders and visionaries. Crafted with unparalleled attention to detail, the Day-Date is the ultimate symbol of refined taste.'),
  ('Rolex', 'GMT-Master', 20500, ' Elevate your style with the Rolex GMT-Master, an icon of prestige and luxury. Designed for globetrotters and adventurers, this timepiece features a dual time zone function, allowing you to keep track of multiple time zones with ease. The GMT-Master is a companion for those who navigate the world with sophistication.'),
  ('Rolex', 'Milgauss', 15000, 'The Rolex Milgauss is an icon of prestige and luxury, designed for those who appreciate innovation and style. Known for its resistance to magnetic fields, this watch is a testament to Rolex''s commitment to cutting-edge technology. The Milgauss is a statement of both form and function.'),
  ('Omega', 'Moonwatch', 5000, 'Experience the allure of space with the Omega Moonwatch, a legendary timepiece that has ventured beyond our atmosphere. Worn by astronauts during the Apollo missions, this watch is a symbol of human achievement and exploration. The Moonwatch is a tribute to the spirit of discovery.'),
  ('Patek Philippe', 'Nautilus', 60000, 'Embrace the epitome of elegance with the Patek Philippe Nautilus, an exquisite luxury watch. With its distinctive porthole design, the Nautilus is a symbol of sophistication and refinement. Crafted with the utmost attention to detail, this watch is a '),
  ('Hublot', 'Big Bang', 69000, 'The Hublot Big Bang is a testament to exceptional craftsmanship and avant-garde design. Blending innovation with bold aesthetics, this watch is a statement of individuality and style. The Big Bang is a celebration of creativity and artistry.'),
  ('Tag Heuer', 'Monaco', 7500, 'The Tag Heuer Monaco is a tribute to exceptional craftsmanship and timeless design. Known for its square case and distinctive blue dial, this watch is an icon of racing heritage. The Monaco is a symbol of daring and innovation. Featured in Breaking Bad.'),
  ('Tudor', 'Black Bay', 4500, 'The Tudor Black Bay is a testament to exceptional craftsmanship and rugged elegance. Inspired by the rich maritime history of Tudor, this watch combines vintage charm with modern reliability. The Black Bay is a companion for those who seek adventure and style.');
